site_name: xmrSale
site_url: https://xmrsale.org/
theme:
  name: material
  palette:
    primary: deep orange
    accent: grey
  logo: assets/xmr-logo-outlined.png
  favicon: assets/favicon.ico

nav:
  - 'index.md'
  - 'install.md'
  - 'woocommerce.md'
  - 'HTTPS.md'
  - 'tor.md'
